services:
  ipfs: # The interplanetary file system where the NFTs metadata and images are hosted
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - /ipfs/data:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
  salmon: # Smart Contracts
    build:
      context: ./packages/salmon
      dockerfile: Dockerfile
    restart: always
    command: yarn run dev
    volumes:
      - ./packages/salmon:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:8545:8545"
  goldfish: # Website
    build:
      context: ./packages/goldfish
      dockerfile: Dockerfile
    restart: always
    command: node server.js
    ports:
      - "0.0.0.0:80:3000"
    volumes:
      - ./packages/goldfish:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

# postgres could be added if whale used postgres instead of supabase