services:
  postgres:
    container_name: 'db'
    image: 'postgres:latest'
    restart: always
    ports:
      - '15432:5432'
    networks:
      - app-tier
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      # - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: 'dpage/pgadmin4'
    restart: always
    ports:
      - '5050:80'
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: 'test@test.com'
      PGADMIN_DEFAULT_PASSWORD: 'test'
    networks:
      - app-tier

  ipfs: # The interplanetary file system where the NFTs metadata and images are hosted
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - /ipfs/data:/ipfsdata
    ports:
      - '4001:4001'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:5001:5001'
  salmon: # Smart Contracts
    build:
      context: ./packages/salmon
      dockerfile: Dockerfile
    restart: always
    command: yarn run dev
    volumes:
      - ./packages/salmon:/app
      - /app/node_modules
    ports:
      - '0.0.0.0:8545:8545'
  goldfish: # Website
    build:
      context: ./packages/goldfish
      dockerfile: Dockerfile
    networks:
      - app-tier
    command: yarn run dev
    ports:
      - '80:3000'
    volumes:
      - ./packages/goldfish:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./packages/goldfish/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/aquarium-wars
      - SHADOW_DATABASE_URL=postgres://postgres:postgres@db/shadow_db

networks:
  app-tier:
    driver: bridge