services:
  ipfs: # The interplanetary file system where the NFTs metadata and images are hosted
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - /ipfs/data:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"

# postgres could be added if whale used postgres instead of supabase